POST http://localhost:8000/groups/
Content-Type: application/json

{
  "name": "Helicopter pilots"
}

###

PUT http://localhost:8000/groups/2/
Content-Type: application/json

{
  "name": "Helicopter pilotz"
}

###

GET http://localhost:8000/groups/

###

# User 1
POST http://localhost:8000/users/
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith",
  "email": "john.smith@company.com",
  "isActive": true,
  "group": 1
}

###

# User 2
POST http://localhost:8000/users/
Content-Type: application/json

{
  "firstName": "Kate",
  "lastName": "Smith",
  "email": "kate.smith@company.com",
  "isActive": true,
  "group": 1
}

###

# User 3
PUT http://localhost:8000/users/7/
Content-Type: application/json

{
  "firstName": "Elton",
  "lastName": "John",
  "email": "elton.john@gmail.com",
  "isActive": true,
  "group": 1
}

###

GET http://localhost:8000/users/

###