POST http://localhost:8000/groups/
Content-Type: application/json

{
  "name": "Helicopter pilots"
}

###

GET http://localhost:8000/groups/

###

POST http://localhost:8000/users/
Content-Type: application/json

{
  "firstName": "Elon",
  "lastName": "Musk",
  "email": "ElonMuskOffice@TeslaMotors.com",
  "isActive": true,
  "groupId": 1
}

###
